import type { Product } from "@/types";

export const NAV_LINKS = [
  { label: "HOME", href: "/" },
  { label: "SHOP ALL", href: "/shop" },
  { label: "OUR STORY", href: "/our-story" },
  { label: "CONTACT", href: "/contact" },
] as const;

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: "TITAN PRE-WORKOUT",
    slug: "titan-pre-workout",
    category: "Pre-Workout",
    price: 49.99,
    rating: 4.9,
    reviewCount: 2341,
    badge: "BEST SELLER",
    flavors: ["#FF4B4B", "#1E90FF", "#00C896", "#FFD700"],
    sizes: ["30 Servings", "60 Servings"],
    description:
      "Explosive energy formula with 350mg caffeine, beta-alanine, and citrulline malate. Fuel every rep with Titan.",
    image: "https://res.cloudinary.com/dsejihoyr/image/upload/v1773786244/preworkout-titan_mcci95.png",
  },
  {
    id: 2,
    name: "WHEY GOLD PROTEIN",
    slug: "whey-gold-protein",
    category: "Protein",
    price: 59.99,
    rating: 4.8,
    reviewCount: 3120,
    badge: "BEST SELLER",
    flavors: ["#8B4513", "#F5DEB3", "#FFFDD0", "#D2691E"],
    sizes: ["2 lbs", "5 lbs", "10 lbs"],
    description:
      "25g of ultra-pure whey protein per serving. Fast-absorbing formula for maximum muscle recovery and growth.",
    image: "https://res.cloudinary.com/dsejihoyr/image/upload/v1773786243/wheygold-protein_yyrrpl.png",
  },
  {
    id: 3,
    name: "ULTRA BCAA 2:1:1",
    slug: "ultra-bcaa",
    category: "Amino Acids",
    price: 34.99,
    rating: 4.7,
    reviewCount: 1875,
    badge: "NEW",
    flavors: ["#FF69B4", "#00CED1", "#7B68EE", "#32CD32"],
    sizes: ["30 Servings", "60 Servings", "90 Servings"],
    description:
      "Optimal 2:1:1 ratio of leucine, isoleucine, and valine. Accelerate recovery and reduce muscle soreness.",
    image: "https://res.cloudinary.com/dsejihoyr/image/upload/v1773786243/BCAA_tcsg3t.png",
  },
  {
    id: 4,
    name: "CREATINE MONO",
    slug: "creatine-mono",
    category: "Amino Acids",
    price: 29.99,
    rating: 4.9,
    reviewCount: 4210,
    badge: "BEST SELLER",
    flavors: ["#FFFFFF", "#D3D3D3"],
    sizes: ["250g", "500g", "1kg"],
    description:
      "Pure micronized creatine monohydrate. Clinically proven to increase strength, power, and muscle mass.",
    image: "https://res.cloudinary.com/dsejihoyr/image/upload/v1773786243/creatine-mono_x1lyuh.png",
  },
  {
    id: 5,
    name: "IRON MASS GAINER",
    slug: "iron-mass-gainer",
    category: "Protein",
    price: 69.99,
    rating: 4.6,
    reviewCount: 987,
    badge: "MAS VENDIDO",
    flavors: ["#8B4513", "#F5DEB3", "#C0C0C0"],
    sizes: ["5 lbs", "10 lbs"],
    description:
      "1000 calories per serving with 50g protein and complex carbohydrates. Engineered for serious size and strength gains.",
    image: "https://res.cloudinary.com/dsejihoyr/image/upload/v1773786243/mass-gainer_z7f4ja.png",
  },
  {
    id: 6,
    name: "MULTI COMPLEX",
    slug: "multi-complex",
    category: "Vitamins",
    price: 24.99,
    rating: 4.7,
    reviewCount: 542,
    badge: "NEW",
    flavors: ["#FFD700"],
    sizes: ["30 Count", "60 Count", "90 Count"],
    description:
      "Complete daily vitamin and mineral complex formulated for high-performance athletes. 23 essential nutrients.",
    image: "https://res.cloudinary.com/dsejihoyr/image/upload/v1773786243/multi-plex_ia5u4q.png",
  },
  {
    id: 7,
    name: "PURE GLUTAMINE",
    slug: "pure-glutamine",
    category: "Amino Acids",
    price: 19.99,
    rating: 4.8,
    reviewCount: 764,
    badge: null,
    flavors: ["#FFFFFF", "#D3D3D3"],
    sizes: ["250g", "500g", "1kg"],
    description:
      "100% pure L-glutamine powder for muscle recovery, gut health, and immune support. Unflavored and easy to mix.",
    image: "https://res.cloudinary.com/dsejihoyr/image/upload/v1773786243/glutamine_nxxuua.png",
  },
  {
    id: 8,
    name: "OMEGA 3 ULTRA",
    slug: "omega-3-ultra",
    category: "Vitamins",
    price: 18.99,
    rating: 4.9,
    reviewCount: 2098,
    badge: "BEST SELLER",
    flavors: ["#FFD700"],
    sizes: ["60 Softgels", "120 Softgels", "180 Softgels"],
    description:
      "Pharmaceutical-grade omega-3 fatty acids with 1200mg EPA/DHA per serving. Supports heart, brain, and joint health.",
    image: "https://res.cloudinary.com/dsejihoyr/image/upload/v1773786243/omega3_ookc3m.png",
  },
];
